import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "var(--on-error)",
        "lead-ordered-text": "var(--lead-ordered-text)",
        "lead-potential-text": "var(--lead-potential-text)",
        "tertiary-container": "var(--tertiary-container)",
        "surface-dim": "var(--surface-dim)",
        "surface-container-low": "var(--surface-container-low)",
        "text-inverse": "var(--text-inverse)",
        "info": "var(--info)",
        "border-strong": "var(--border-strong)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "lead-asnef-bg": "var(--lead-asnef-bg)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "primary-fixed": "var(--primary-fixed)",
        "surface-container": "var(--surface-container)",
        "on-primary-container": "var(--on-primary-container)",
        "lead-waiting-bg": "var(--lead-waiting-bg)",
        "on-error-container": "var(--on-error-container)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "text-primary": "var(--text-primary)",
        "on-background": "var(--on-background)",
        "on-secondary-container": "var(--on-secondary-container)",
        "lead-no-reply-bg": "var(--lead-no-reply-bg)",
        "lead-waiting-text": "var(--lead-waiting-text)",
        "on-tertiary": "var(--on-tertiary)",
        "lead-rejected-text": "var(--lead-rejected-text)",
        "danger": "var(--danger)",
        "error-container": "var(--error-container)",
        "success": "var(--success)",
        "lead-unfinanceable-bg": "var(--lead-unfinanceable-bg)",
        "bg-input": "var(--bg-input)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "text-secondary": "var(--text-secondary)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "text-disabled": "var(--text-disabled)",
        "lead-unfinanceable-text": "var(--lead-unfinanceable-text)",
        "lead-potential-bg": "var(--lead-potential-bg)",
        "bg-base": "var(--bg-base)",
        "lead-quarantine-bg": "var(--lead-quarantine-bg)",
        "outline": "var(--outline)",
        "lead-ordering-bg": "var(--lead-ordering-bg)",
        "outline-variant": "var(--outline-variant)",
        "inverse-surface": "var(--inverse-surface)",
        "surface-container-highest": "var(--surface-container-highest)",
        "border-default": "var(--border-default)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-surface": "var(--on-surface)",
        "tertiary": "var(--tertiary)",
        "secondary": "var(--secondary)",
        "error": "var(--error)",
        "on-primary": "var(--on-primary)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "border-subtle": "var(--border-subtle)",
        "text-tertiary": "var(--text-tertiary)",
        "background": "var(--background)",
        "lead-no-reply-text": "var(--lead-no-reply-text)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-secondary": "var(--on-secondary)",
        "surface": "var(--surface)",
        "surface-container-high": "var(--surface-container-high)",
        "bg-elevated": "var(--bg-elevated)",
        "surface-bright": "var(--surface-bright)",
        "lead-ordered-bg": "var(--lead-ordered-bg)",
        "primary": "var(--primary)",
        "secondary-container": "var(--secondary-container)",
        "primary-container": "var(--primary-container)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "accent-glow": "var(--accent-glow)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "surface-tint": "var(--surface-tint)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "bg-surface": "var(--bg-surface)",
        "lead-asnef-text": "var(--lead-asnef-text)",
        "lead-quarantine-text": "var(--lead-quarantine-text)",
        "surface-variant": "var(--surface-variant)",
        "inverse-primary": "var(--inverse-primary)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "warning": "var(--warning)",
        "on-surface-variant": "var(--on-surface-variant)",
        "lead-rejected-bg": "var(--lead-rejected-bg)",
        "lead-ordering-text": "var(--lead-ordering-text)",
        "lead-asnef-text-light": "var(--lead-asnef-text-light)",
        "lead-potential-bg-light": "var(--lead-potential-bg-light)",
        "lead-quarantine-bg-light": "var(--lead-quarantine-bg-light)",
        "lead-ordered-bg-light": "var(--lead-ordered-bg-light)",
        "lead-waiting-bg-light": "var(--lead-waiting-bg-light)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "unit": "4px",
        "gutter-sm": "16px",
        "max-width": "1440px",
        "header-height": "56px",
        "sidebar-wide": "240px",
        "gutter-md": "24px",
        "sidebar-collapsed": "64px",
      },
      fontFamily: {
        "display-welcome": ["var(--font-inter)"],
        "body-base": ["var(--font-inter)"],
        "kpi-headline": ["var(--font-inter)"],
        "label-xs": ["var(--font-inter)"],
        "body-sm": ["var(--font-inter)"],
        "page-title": ["var(--font-inter)"],
        "field-label": ["var(--font-inter)"],
        "section-subtitle": ["var(--font-inter)"],
        "data-mono": ["var(--font-jetbrains-mono)"],
        "body-md": ["var(--font-inter)"],
        "headline-lg": ["var(--font-hanken-grotesk)"],
        "label-md": ["var(--font-jetbrains-mono)"],
        "display-lg": ["var(--font-hanken-grotesk)"],
      },
      fontSize: {
        "display-welcome": ["36px", { lineHeight: "1.1", fontWeight: "700" }],
        "body-base": ["15px", { lineHeight: "1.6", fontWeight: "400" }],
        "kpi-headline": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-xs": ["11px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "page-title": ["21px", { lineHeight: "1.3", fontWeight: "600" }],
        "field-label": ["11px", { letterSpacing: "0.08em", fontWeight: "400" }],
        "section-subtitle": ["17px", { lineHeight: "1.5", fontWeight: "500" }],
        "data-mono": ["14px", { lineHeight: "1.4", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
