import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "lead-ordered-text": "#34D399",
        "lead-potential-text": "#818CF8",
        "tertiary-container": "#db761f",
        "surface-dim": "#13121b",
        "surface-container-low": "#1b1b24",
        "text-inverse": "#0A0B0F",
        "info": "#60A5FA",
        "border-strong": "#3D445A",
        "on-primary-fixed": "#100069",
        "lead-asnef-bg": "#2D1A1A",
        "tertiary-fixed": "#ffdcc6",
        "primary-fixed": "#e3dfff",
        "surface-container": "#1f1f28",
        "on-primary-container": "#1b0091",
        "lead-waiting-bg": "#1E1128",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#301400",
        "text-primary": "#F0F2FF",
        "on-background": "#e4e1ee",
        "on-secondary-container": "#005669",
        "lead-no-reply-bg": "#2D1D00",
        "lead-waiting-text": "#C084FC",
        "on-tertiary": "#502500",
        "lead-rejected-text": "#DC2626",
        "danger": "#F87171",
        "error-container": "#93000a",
        "success": "#34D399",
        "lead-unfinanceable-bg": "#1A1C22",
        "bg-input": "#13151C",
        "on-tertiary-container": "#461f00",
        "text-secondary": "#8B90A8",
        "tertiary-fixed-dim": "#ffb785",
        "text-disabled": "#2E3245",
        "lead-unfinanceable-text": "#6B7280",
        "lead-potential-bg": "#1A1F3A",
        "bg-base": "#0A0B0F",
        "lead-quarantine-bg": "#2D2400",
        "outline": "#918fa1",
        "lead-ordering-bg": "#001E28",
        "outline-variant": "#464555",
        "inverse-surface": "#e4e1ee",
        "surface-container-highest": "#35343e",
        "border-default": "#2A2F40",
        "surface-container-lowest": "#0e0d16",
        "on-surface": "#e4e1ee",
        "tertiary": "#ffb785",
        "secondary": "#a2e7ff",
        "error": "#ffb4ab",
        "on-primary": "#2000a4",
        "on-tertiary-fixed-variant": "#713700",
        "border-subtle": "#1F2330",
        "text-tertiary": "#4E5368",
        "background": "#13121b",
        "lead-no-reply-text": "#FB923C",
        "secondary-fixed": "#b4ebff",
        "on-secondary": "#003642",
        "surface": "#13121b",
        "surface-container-high": "#2a2933",
        "bg-elevated": "#1A1D24",
        "surface-bright": "#393842",
        "lead-ordered-bg": "#0A2018",
        "primary": "#c4c0ff",
        "secondary-container": "#00d2fd",
        "primary-container": "#8781ff",
        "on-secondary-fixed": "#001f27",
        "accent-glow": "rgba(108, 99, 255, 0.2)",
        "on-primary-fixed-variant": "#3622ca",
        "secondary-fixed-dim": "#3cd7ff",
        "inverse-on-surface": "#302f39",
        "surface-tint": "#c4c0ff",
        "on-secondary-fixed-variant": "#004e5f",
        "bg-surface": "#111318",
        "lead-asnef-text": "#F87171",
        "lead-quarantine-text": "#FCD34D",
        "surface-variant": "#35343e",
        "inverse-primary": "#4f44e2",
        "primary-fixed-dim": "#c4c0ff",
        "warning": "#FCD34D",
        "on-surface-variant": "#c7c4d8",
        "lead-rejected-bg": "#200A0A",
        "lead-ordering-text": "#22D3EE",
        "lead-asnef-text-light": "#ef4444",
        "lead-potential-bg-light": "rgba(129, 140, 248, 0.1)",
        "lead-quarantine-bg-light": "rgba(252, 211, 77, 0.1)",
        "lead-ordered-bg-light": "rgba(52, 211, 153, 0.1)",
        "lead-waiting-bg-light": "rgba(192, 132, 252, 0.1)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "unit": "4px",
        "gutter-sm": "16px",
        "max-width": "1440px",
        "header-height": "56px",
        "sidebar-wide": "240px",
        "gutter-md": "24px",
        "sidebar-collapsed": "64px",
      },
      fontFamily: {
        "display-welcome": ["var(--font-inter)"],
        "body-base": ["var(--font-inter)"],
        "kpi-headline": ["var(--font-inter)"],
        "label-xs": ["var(--font-inter)"],
        "body-sm": ["var(--font-inter)"],
        "page-title": ["var(--font-inter)"],
        "field-label": ["var(--font-inter)"],
        "section-subtitle": ["var(--font-inter)"],
        "data-mono": ["var(--font-jetbrains-mono)"],
        "body-md": ["var(--font-inter)"],
        "headline-lg": ["var(--font-hanken-grotesk)"],
        "label-md": ["var(--font-jetbrains-mono)"],
        "display-lg": ["var(--font-hanken-grotesk)"],
      },
      fontSize: {
        "display-welcome": ["36px", { lineHeight: "1.1", fontWeight: "700" }],
        "body-base": ["15px", { lineHeight: "1.6", fontWeight: "400" }],
        "kpi-headline": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-xs": ["11px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "page-title": ["21px", { lineHeight: "1.3", fontWeight: "600" }],
        "field-label": ["11px", { letterSpacing: "0.08em", fontWeight: "400" }],
        "section-subtitle": ["17px", { lineHeight: "1.5", fontWeight: "500" }],
        "data-mono": ["14px", { lineHeight: "1.4", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
